# applications/base/redis/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # echo -n "your-secure-password" | base64
  REDIS_PASSWORD: eW91ci1zZWN1cmUtcGFzc3dvcmQ= # "your-secure-password" in base64
