# PersistentVolume for local dev (Docker Desktop).
# Uses node's disk so the PVC has something to bind to.
# In the cloud you'd use a StorageClass instead; this PV wouldn't exist.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate
