# Postgres password. Change the value before production!
# Generate new: echo -n "yourpassword" | base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: changeme_local_only
  POSTGRES_DB: appdb
