apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQ= # "postgres-password"
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzLXBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0Z3Jlcw==
